/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Accept1Enum
 */
export enum Accept1Enum {
  EnumApplicationjson = 'application/json',
  EnumTextcsv = 'text/csv',
}

/**
 * Schema for Accept1Enum
 */
export const accept1EnumSchema: Schema<Accept1Enum> = stringEnum(Accept1Enum);
