/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AcceptEnum
 */
export enum AcceptEnum {
  EnumApplicationjson = 'application/json',
  EnumTextcsv = 'text/csv',
}

/**
 * Schema for AcceptEnum
 */
export const acceptEnumSchema: Schema<AcceptEnum> = stringEnum(AcceptEnum);
