/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface APIKeyNameIDandScopes {
  /** The permissions this API Key has access to. */
  scopes?: string[];
  /** The ID of your API Key. */
  apiKeyId?: string;
  /** The name of your API Key. */
  name?: string;
}

export const aPIKeyNameIDandScopesSchema: Schema<APIKeyNameIDandScopes> = object(
  {
    scopes: ['scopes', optional(array(string()))],
    apiKeyId: ['api_key_id', optional(string())],
    name: ['name', optional(string())],
  }
);
