/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Metadata1, metadata1Schema } from './metadata1';
import { Results3, results3Schema } from './results3';

export interface AutomationsResponse {
  results: Results3[];
  metadata?: Metadata1;
}

export const automationsResponseSchema: Schema<AutomationsResponse> = object({
  results: ['results', array(lazy(() => results3Schema))],
  metadata: ['_metadata', optional(lazy(() => metadata1Schema))],
});
