/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface Createmonitorsettingsrequest {
  /** The email address to which Sendgrid should send emails for monitoring. */
  email: string;
  /** The frequency at which to forward monitoring emails. An email will be sent when your subuser sends this many (e.g., 1,000) emails. */
  frequency: number;
}

export const createmonitorsettingsrequestSchema: Schema<Createmonitorsettingsrequest> = object(
  { email: ['email', string()], frequency: ['frequency', number()] }
);
