/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Dkim2, dkim2Schema } from './dkim2';
import { MailCname3, mailCname3Schema } from './mailCname3';

export interface Dns3 {
  mailCname: MailCname3;
  dkim1: Dkim2;
  dkim2: Dkim2;
}

export const dns3Schema: Schema<Dns3> = object({
  mailCname: ['mail_cname', lazy(() => mailCname3Schema)],
  dkim1: ['dkim1', lazy(() => dkim2Schema)],
  dkim2: ['dkim2', lazy(() => dkim2Schema)],
});
