/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { DomainCname3, domainCname3Schema } from './domainCname3';
import { OwnerCname3, ownerCname3Schema } from './ownerCname3';

export interface Dns5 {
  domainCname: DomainCname3;
  ownerCname?: OwnerCname3;
}

export const dns5Schema: Schema<Dns5> = object({
  domainCname: ['domain_cname', lazy(() => domainCname3Schema)],
  ownerCname: ['owner_cname', optional(lazy(() => ownerCname3Schema))],
});
