/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema';

export interface DomainSpf2 {
  /** The root domain that this SPF record will be used to authenticate. */
  host: string;
  /** The type of data in the SPF record. */
  type: string;
  /** The SPF record. */
  data: string;
  /** Indicates if the SPF record is valid. */
  valid: boolean;
}

export const domainSpf2Schema: Schema<DomainSpf2> = object({
  host: ['host', string()],
  type: ['type', string()],
  data: ['data', string()],
  valid: ['valid', boolean()],
});
