/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Editor4Enum, editor4EnumSchema } from './editor4Enum';

export interface EmailConfig {
  /** The subject line of the Single Send. Do not include this field when using a `design_id`. */
  subject?: string;
  /** The HTML content of the Single Send. Do not include this field when using a `design_id`. */
  htmlContent?: string;
  /** The plain text content of the Single Send. Do not include this field when using a `design_id`. */
  plainContent?: string;
  /** If set to `true`, `plain_content` is always generated from `html_content`. If set to false, `plain_content` is not altered. */
  generatePlainContent?: boolean;
  /** A `design_id` can be used in place of `html_content`, `plain_content`, and/or `subject`. You can retrieve a design's ID from the ["List Designs" endpoint](https://sendgrid.api-docs.io/v3.0/designs-api/list-designs) or by pulling it from the design's detail page URL in the Marketing Campaigns App. */
  designId?: string;
  editor?: Editor4Enum;
  /** The ID of the Suppression Group to allow recipients to unsubscribe — you must provide this or the `custom_unsubscribe_url`. */
  suppressionGroupId?: number | null;
  /** The URL allowing recipients to unsubscribe — you must provide this or the `suppression_group_id`. */
  customUnsubscribeUrl?: string | null;
  /** The ID of the verified Sender. You can retrieve a verified Sender's ID from the ["Get Verified Senders" endpoint](https://sendgrid.api-docs.io/v3.0/sender-verification/get-verified-senders) or by pulling it from the Sender's detail page URL in the SendGrid App. */
  senderId?: number | null;
  /** The name of the IP Pool from which the Single Send emails are sent. */
  ipPool?: string | null;
}

export const emailConfigSchema: Schema<EmailConfig> = object({
  subject: ['subject', optional(string())],
  htmlContent: ['html_content', optional(string())],
  plainContent: ['plain_content', optional(string())],
  generatePlainContent: ['generate_plain_content', optional(boolean())],
  designId: ['design_id', optional(string())],
  editor: ['editor', optional(editor4EnumSchema)],
  suppressionGroupId: ['suppression_group_id', optional(nullable(number()))],
  customUnsubscribeUrl: [
    'custom_unsubscribe_url',
    optional(nullable(string())),
  ],
  senderId: ['sender_id', optional(nullable(number()))],
  ipPool: ['ip_pool', optional(nullable(string()))],
});
