/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Errors33, errors33Schema } from './errors33';

/** If the request is incorrect, an array of errors will be returned. */
export interface ErrorsSeg1 {
  errors: Errors33[];
}

export const errorsSeg1Schema: Schema<ErrorsSeg1> = object({
  errors: ['errors', array(lazy(() => errors33Schema))],
});
