/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Errors9 {
  message?: string;
  field?: string;
}

export const errors9Schema: Schema<Errors9> = object({
  message: ['message', optional(string())],
  field: ['field', optional(string())],
});
