/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Errors18 {
  /** A message explaining the reason for the error. */
  message: string;
}

export const errors18Schema: Schema<Errors18> = object({
  message: ['message', string()],
});
