/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for EventNameEnum
 */
export enum EventNameEnum {
  Bounced = 'bounced',
  Opened = 'opened',
  Clicked = 'clicked',
  Processed = 'processed',
  Dropped = 'dropped',
  Delivered = 'delivered',
  Deferred = 'deferred',
  SpamReport = 'spam_report',
  Unsubscribe = 'unsubscribe',
  GroupUnsubscribe = 'group_unsubscribe',
  GroupResubscribe = 'group_resubscribe',
}

/**
 * Schema for EventNameEnum
 */
export const eventNameEnumSchema: Schema<EventNameEnum> = stringEnum(EventNameEnum);
