/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FileTypeEnum
 */
export enum FileTypeEnum {
  Csv = 'csv',
  Json = 'json',
}

/**
 * Schema for FileTypeEnum
 */
export const fileTypeEnumSchema: Schema<FileTypeEnum> = stringEnum(FileTypeEnum);
