/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface From {
  /** This is where the email will appear to originate from for your recipient */
  email: string;
  /** This is the name appended to the from email field. IE - Your name or company name. */
  name: string;
}

export const fromSchema: Schema<From> = object({
  email: ['email', string()],
  name: ['name', string()],
});
