/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Generation1Enum
 */
export enum Generation1Enum {
  Legacy = 'legacy',
  Dynamic = 'dynamic',
}

/**
 * Schema for Generation1Enum
 */
export const generation1EnumSchema: Schema<Generation1Enum> = stringEnum(Generation1Enum);
