/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface InvalidEmail {
  /** A Unix timestamp indicating when the email address was added to the invalid emails list. */
  created?: number;
  /** The email address that was marked as invalid. */
  email?: string;
  /** The reason that the email address was marked as invalid. */
  reason?: string;
}

export const invalidEmailSchema: Schema<InvalidEmail> = object({
  created: ['created', optional(number())],
  email: ['email', optional(string())],
  reason: ['reason', optional(string())],
});
