/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface Ip1 {
  /** IP added to account. */
  ip: string;
  /** Array of usernames assigned a send IP. */
  subusers: string[];
}

export const ip1Schema: Schema<Ip1> = object({
  ip: ['ip', string()],
  subusers: ['subusers', array(string())],
});
