/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Dns5, dns5Schema } from './dns5';

export interface LinkBranding200Response {
  /** The ID of the branded link. */
  id: number;
  /** The root domain of the branded link. */
  domain: string;
  /** The subdomain used to generate the DNS records for this link branding. This subdomain must be different from the subdomain used for your authenticated domain. */
  subdomain?: string;
  /** The username of the account that this link branding is associated with. */
  username: string;
  /** The ID of the user that this link branding is associated with. */
  userId: number;
  /** Indicates if this is the default link branding. */
  mDefault: boolean;
  /** Indicates if this link branding is valid. */
  valid: boolean;
  /** Indicates if this link branding was created using the legacy whitelabel tool. If it is a legacy whitelabel, it will still function, but you'll need to create new link branding if you need to update it. */
  legacy: boolean;
  dns: Dns5;
}

export const linkBranding200ResponseSchema: Schema<LinkBranding200Response> = object(
  {
    id: ['id', number()],
    domain: ['domain', string()],
    subdomain: ['subdomain', optional(string())],
    username: ['username', string()],
    userId: ['user_id', number()],
    mDefault: ['default', boolean()],
    valid: ['valid', boolean()],
    legacy: ['legacy', boolean()],
    dns: ['dns', lazy(() => dns5Schema)],
  }
);
