/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import {
  CreateaSegmentrequest,
  createaSegmentrequestSchema,
} from './createaSegmentrequest';

export interface ListAllSegmentsresponse {
  segments: CreateaSegmentrequest[];
}

export const listAllSegmentsresponseSchema: Schema<ListAllSegmentsresponse> = object(
  { segments: ['segments', array(lazy(() => createaSegmentrequestSchema))] }
);
