/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Metadata3 {
  prev?: string;
  /** Link to this page. */
  self?: string;
  /** Link to next page. */
  next?: string;
}

export const metadata3Schema: Schema<Metadata3> = object({
  prev: ['prev', optional(string())],
  self: ['self', optional(string())],
  next: ['next', optional(string())],
});
