/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

export interface Metrics2 {
  bounceDrops: number;
  bounces: number;
  clicks: number;
  delivered: number;
  invalidEmails: number;
  opens: number;
  requests: number;
  spamReportDrops: number;
  spamReports: number;
  uniqueClicks: number;
  uniqueOpens: number;
  unsubscribes: number;
}

export const metrics2Schema: Schema<Metrics2> = object({
  bounceDrops: ['bounce_drops', number()],
  bounces: ['bounces', number()],
  clicks: ['clicks', number()],
  delivered: ['delivered', number()],
  invalidEmails: ['invalid_emails', number()],
  opens: ['opens', number()],
  requests: ['requests', number()],
  spamReportDrops: ['spam_report_drops', number()],
  spamReports: ['spam_reports', number()],
  uniqueClicks: ['unique_clicks', number()],
  uniqueOpens: ['unique_opens', number()],
  unsubscribes: ['unsubscribes', number()],
});
