/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface Metrics8 {
  /** The number of links that were clicked in your emails. */
  clicks?: number;
  /** The number of unique recipients who clicked links in your emails. */
  uniqueClicks?: number;
}

export const metrics8Schema: Schema<Metrics8> = object({
  clicks: ['clicks', optional(number())],
  uniqueClicks: ['unique_clicks', optional(number())],
});
