/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Results5 {
  /** This is the URL of the link clicked. If `{{custom_fields}}` are part of the URL, they will be included. */
  url: string;
  /** This is the location of the link clicked in each Automation step. Links are located according to their position within the message; the topmost link has index `0`. */
  urlLocation?: number;
  /** This is the ID of the step if the stats were requested to be grouped by `step_id`. */
  stepId: string;
  /** The number of clicks on this particular link. */
  clicks: number;
}

export const results5Schema: Schema<Results5> = object({
  url: ['url', string()],
  urlLocation: ['url_location', optional(number())],
  stepId: ['step_id', string()],
  clicks: ['clicks', number()],
});
