/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface RetrieveaGlobalSuppressionresponse {
  /** The email address that is globally suppressed. This will be an empty object if the email address you included in your call is not globally suppressed. */
  recipientEmail: string;
}

export const retrieveaGlobalSuppressionresponseSchema: Schema<RetrieveaGlobalSuppressionresponse> = object(
  { recipientEmail: ['recipient_email', string()] }
);
