/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

export interface ScheduleaCampaignrequest {
  /** The unix timestamp for the date and time you would like your campaign to be sent out. */
  sendAt: number;
}

export const scheduleaCampaignrequestSchema: Schema<ScheduleaCampaignrequest> = object(
  { sendAt: ['send_at', number()] }
);
