/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Status3Enum, status3EnumSchema } from './status3Enum';

export interface SinglesendSchedule {
  /** The ISO 8601 time at which to send the Single Send. This must be in future or the string "now". Emails can be scheduled up to 72 hours in advance. However, this scheduling constraint does not apply to campaigns sent via [Marketing Campaigns](https://docs.sendgrid.com/ui/sending-email/how-to-send-email-with-marketing-campaigns/). */
  sendAt: string;
  status?: Status3Enum;
}

export const singlesendScheduleSchema: Schema<SinglesendSchedule> = object({
  sendAt: ['send_at', string()],
  status: ['status', optional(status3EnumSchema)],
});
