/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface SingleSignOnCertificateBody {
  /** This certificate is used by Twilio SendGrid to verify that SAML requests are coming from Okta. This is called the X509 certificate in the Twilio SendGrid UI. */
  publicCertificate?: string;
  /** A unique ID assigned to the certificate by SendGrid. */
  id?: number;
  /** A unix timestamp (e.g., 1603915954) that indicates the time before which the certificate is not valid. */
  notBefore?: number;
  /** A unix timestamp (e.g., 1603915954) that indicates the time after which the certificate is no longer valid. */
  notAfter?: number;
  /** An ID that matches a certificate to a specific IdP integration. */
  intergrationId?: string;
}

export const singleSignOnCertificateBodySchema: Schema<SingleSignOnCertificateBody> = object(
  {
    publicCertificate: ['public_certificate', optional(string())],
    id: ['id', optional(number())],
    notBefore: ['not_before', optional(number())],
    notAfter: ['not_after', optional(number())],
    intergrationId: ['intergration_id', optional(string())],
  }
);
