/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Metadata1, metadata1Schema } from './metadata1';
import { Results4, results4Schema } from './results4';

export interface SinglesendsResponse {
  results: Results4[];
  metadata: Metadata1;
}

export const singlesendsResponseSchema: Schema<SinglesendsResponse> = object({
  results: ['results', array(lazy(() => results4Schema))],
  metadata: ['_metadata', lazy(() => metadata1Schema)],
});
