/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SortByMetric1Enum
 */
export enum SortByMetric1Enum {
  Blocks = 'blocks',
  Bounces = 'bounces',
  Clicks = 'clicks',
  Delivered = 'delivered',
  Opens = 'opens',
  Requests = 'requests',
  UniqueClicks = 'unique_clicks',
  UniqueOpens = 'unique_opens',
  Unsubscribes = 'unsubscribes',
}

/**
 * Schema for SortByMetric1Enum
 */
export const sortByMetric1EnumSchema: Schema<SortByMetric1Enum> = stringEnum(SortByMetric1Enum);
