/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, nullable, object, optional, Schema, string } from '../schema';

/** The SPF record for the authenticated domain. */
export interface Spf {
  /** Indicates if the SPF record is valid. */
  valid?: boolean;
  reason?: string | null;
}

export const spfSchema: Schema<Spf> = object({
  valid: ['valid', optional(boolean())],
  reason: ['reason', optional(nullable(string()))],
});
