/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, nullable, object, optional, Schema, string } from '../schema';

export interface Spf2 {
  /** Indicates if the SPF record is valid. */
  valid?: boolean;
  reason?: string | null;
}

export const spf2Schema: Schema<Spf2> = object({
  valid: ['valid', optional(boolean())],
  reason: ['reason', optional(nullable(string()))],
});
