/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Stat11 {
  domain?: string;
  count?: number;
}

export const stat11Schema: Schema<Stat11> = object({
  domain: ['domain', optional(string())],
  count: ['count', optional(number())],
});
