/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Metrics8, metrics8Schema } from './metrics8';

export interface Stat9 {
  /** The type of segmentation. */
  type?: string;
  /** The name of the specific segmentation. */
  name?: string;
  metrics?: Metrics8;
}

export const stat9Schema: Schema<Stat9> = object({
  type: ['type', optional(string())],
  name: ['name', optional(string())],
  metrics: ['metrics', optional(lazy(() => metrics8Schema))],
});
