/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Status2 {
  /** Status of query validation. PENDING, VALID, or INVALID */
  queryValidation: string;
  /** Describes any errors that were encountered during query validation */
  errorMessage?: string;
}

export const status2Schema: Schema<Status2> = object({
  queryValidation: ['query_validation', string()],
  errorMessage: ['error_message', optional(string())],
});
