/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import {
  ClassificationEnum,
  classificationEnumSchema,
} from './classificationEnum';

export interface Stat10 {
  classification?: ClassificationEnum;
  count?: number;
}

export const stat10Schema: Schema<Stat10> = object({
  classification: ['classification', optional(classificationEnumSchema)],
  count: ['count', optional(number())],
});
