/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Metrics7, metrics7Schema } from './metrics7';

export interface Stat8 {
  /** The type of segmentation. */
  type?: string;
  /** The name of the specific segmentation. */
  name?: string;
  metrics?: Metrics7;
}

export const stat8Schema: Schema<Stat8> = object({
  type: ['type', optional(string())],
  name: ['name', optional(string())],
  metrics: ['metrics', optional(lazy(() => metrics7Schema))],
});
