/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface SuppressionsRequestBody {
  /** The array of email addresses to add or find. */
  recipientEmails: string[];
}

export const suppressionsRequestBodySchema: Schema<SuppressionsRequestBody> = object(
  { recipientEmails: ['recipient_emails', array(string())] }
);
