/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Active1Enum, active1EnumSchema } from './active1Enum';
import { EditorEnum, editorEnumSchema } from './editorEnum';
import { Warning1, warning1Schema } from './warning1';

export interface TransactionalTemplatesVersionOutput {
  warnings?: Warning1[];
  active?: Active1Enum;
  /** Name of the transactional template version. */
  name: string;
  /** The HTML content of the version. Maximum of 1048576 bytes allowed. */
  htmlContent?: string;
  /** Text/plain content of the transactional template version. Maximum of 1048576 bytes allowed. */
  plainContent?: string;
  /** If true, plain_content is always generated from html_content. If false, plain_content is not altered. */
  generatePlainContent?: boolean;
  /** Subject of the new transactional template version. */
  subject: string;
  editor?: EditorEnum;
  /** For dynamic templates only, the mock json data that will be used for template preview and test sends. */
  testData?: string;
  /** ID of the transactional template version. */
  id?: string;
  /** ID of the transactional template. */
  templateId?: string;
  /** The date and time that this transactional template version was updated. */
  updatedAt?: string;
  /** A Thumbnail preview of the template's html content. */
  thumbnailUrl?: string;
}

export const transactionalTemplatesVersionOutputSchema: Schema<TransactionalTemplatesVersionOutput> = object(
  {
    warnings: ['warnings', optional(array(lazy(() => warning1Schema)))],
    active: ['active', optional(active1EnumSchema)],
    name: ['name', string()],
    htmlContent: ['html_content', optional(string())],
    plainContent: ['plain_content', optional(string())],
    generatePlainContent: ['generate_plain_content', optional(boolean())],
    subject: ['subject', string()],
    editor: ['editor', optional(editorEnumSchema)],
    testData: ['test_data', optional(string())],
    id: ['id', optional(string())],
    templateId: ['template_id', optional(string())],
    updatedAt: ['updated_at', optional(string())],
    thumbnailUrl: ['thumbnail_url', optional(string())],
  }
);
