/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type4Enum
 */
export enum Type4Enum {
  UsageAlert = 'usage_alert',
  StatsNotification = 'stats_notification',
}

/**
 * Schema for Type4Enum
 */
export const type4EnumSchema: Schema<Type4Enum> = stringEnum(Type4Enum);
