/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type6Enum
 */
export enum Type6Enum {
  Free = 'free',
  Paid = 'paid',
}

/**
 * Schema for Type6Enum
 */
export const type6EnumSchema: Schema<Type6Enum> = stringEnum(Type6Enum);
