/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { Status8Enum, status8EnumSchema } from './status8Enum';

export interface UserScheduledSendstatus {
  batchId: string;
  status: Status8Enum;
}

export const userScheduledSendstatusSchema: Schema<UserScheduledSendstatus> = object(
  { batchId: ['batch_id', string()], status: ['status', status8EnumSchema] }
);
