/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UserType2Enum
 */
export enum UserType2Enum {
  Admin = 'admin',
  Owner = 'owner',
  Teammate = 'teammate',
}

/**
 * Schema for UserType2Enum
 */
export const userType2EnumSchema: Schema<UserType2Enum> = stringEnum(UserType2Enum);
