/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface V3AlertsRequest1 {
  /**
   * The new email address you want your alert to be sent to.
   * Example: test@example.com
   */
  emailTo?: string;
  /**
   * The new frequency at which to send the stats_notification alert.
   * Example: monthly
   */
  frequency?: string;
  /**
   * The new percentage threshold at which the usage_limit alert will be sent.
   * Example: 90
   */
  percentage?: number;
}

export const v3AlertsRequest1Schema: Schema<V3AlertsRequest1> = object({
  emailTo: ['email_to', optional(string())],
  frequency: ['frequency', optional(string())],
  percentage: ['percentage', optional(number())],
});
