/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';
import { Type2Enum, type2EnumSchema } from './type2Enum';

export interface V3AlertsRequest {
  type: Type2Enum;
  /**
   * The email address the alert will be sent to.
   * Example: test@example.com
   */
  emailTo: string | null;
  /**
   * Required for stats_notification. How frequently the alert will be sent.
   * Example: daily
   */
  frequency?: string;
  /**
   * Required for usage_alert. When this usage threshold is reached, the alert will be sent.
   * Example: 90
   */
  percentage?: number;
}

export const v3AlertsRequestSchema: Schema<V3AlertsRequest> = object({
  type: ['type', type2EnumSchema],
  emailTo: ['email_to', nullable(string())],
  frequency: ['frequency', optional(string())],
  percentage: ['percentage', optional(number())],
});
