/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Status6, status6Schema } from './status6';

export interface V3ContactdbStatusResponse {
  status?: Status6[];
}

export const v3ContactdbStatusResponseSchema: Schema<V3ContactdbStatusResponse> = object(
  { status: ['status', optional(array(lazy(() => status6Schema)))] }
);
