/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { ReservedField, reservedFieldSchema } from './reservedField';

export interface V3ContactdbReservedFieldsResponse {
  reservedFields?: ReservedField[];
}

export const v3ContactdbReservedFieldsResponseSchema: Schema<V3ContactdbReservedFieldsResponse> = object(
  {
    reservedFields: [
      'reserved_fields',
      optional(array(lazy(() => reservedFieldSchema))),
    ],
  }
);
