/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface V3ContactdbCustomFieldsRequest {
  name?: string;
  type?: string;
}

export const v3ContactdbCustomFieldsRequestSchema: Schema<V3ContactdbCustomFieldsRequest> = object(
  { name: ['name', optional(string())], type: ['type', optional(string())] }
);
