/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  DesignOutputSummary,
  designOutputSummarySchema,
} from './designOutputSummary';
import { Metadata, metadataSchema } from './metadata';

export interface V3DesignsPreBuiltsResponse {
  result?: DesignOutputSummary[];
  metadata?: Metadata;
}

export const v3DesignsPreBuiltsResponseSchema: Schema<V3DesignsPreBuiltsResponse> = object(
  {
    result: ['result', optional(array(lazy(() => designOutputSummarySchema)))],
    metadata: ['_metadata', optional(lazy(() => metadataSchema))],
  }
);
