/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Stat4, stat4Schema } from './stat4';

export interface V3GeoStatsResponse {
  /** The date that the statistics were gathered. */
  date?: string;
  /** The list of statistics. */
  stats?: Stat4[];
}

export const v3GeoStatsResponseSchema: Schema<V3GeoStatsResponse> = object({
  date: ['date', optional(string())],
  stats: ['stats', optional(array(lazy(() => stat4Schema)))],
});
