/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface V3IpsPools404Error31 {
  /** An error explaining why the pool could not be deleted. */
  error?: string;
}

export const v3IpsPools404Error31Schema: Schema<V3IpsPools404Error31> = object({
  error: ['error', optional(string())],
});
