/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface V3IpsPoolsIpsRequest {
  /** The IP address that you want to add to the named pool. */
  ip?: string;
}

export const v3IpsPoolsIpsRequestSchema: Schema<V3IpsPoolsIpsRequest> = object({
  ip: ['ip', optional(string())],
});
