/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface V3IpsPoolsIps404Error21 {
  /** An error explaining why the IP address could not be removed from the IP pool. */
  error?: string;
}

export const v3IpsPoolsIps404Error21Schema: Schema<V3IpsPoolsIps404Error21> = object(
  { error: ['error', optional(string())] }
);
