/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  number,
  object,
  Schema,
  string,
} from '../schema';

export interface V3IpsResponse2 {
  /** The IP address. */
  ip: string;
  /** The subusers that can send email using this IP address. */
  subusers: string[];
  /** The reverse DNS record for this IP address. */
  rdns: string;
  /** The list of IP pools that this IP address belongs to. */
  pools: string[];
  /** Indicates if this IP address is currently warming up. */
  warmup: boolean;
  /** The date that the IP address was entered into warmup. */
  startDate: number | null;
  /** Indicates if this IP address is associated with a reverse DNS record. */
  whitelabeled: boolean;
}

export const v3IpsResponse2Schema: Schema<V3IpsResponse2> = object({
  ip: ['ip', string()],
  subusers: ['subusers', array(string())],
  rdns: ['rdns', string()],
  pools: ['pools', array(string())],
  warmup: ['warmup', boolean()],
  startDate: ['start_date', nullable(number())],
  whitelabeled: ['whitelabeled', boolean()],
});
