/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Result3, result3Schema } from './result3';

export interface V3IpsRemainingResponse {
  results: Result3[];
}

export const v3IpsRemainingResponseSchema: Schema<V3IpsRemainingResponse> = object(
  { results: ['results', array(lazy(() => result3Schema))] }
);
