/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface V3MarketingListsResponse7 {
  /** job_id of the async job */
  jobId?: string;
}

export const v3MarketingListsResponse7Schema: Schema<V3MarketingListsResponse7> = object(
  { jobId: ['job_id', optional(string())] }
);
