/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { UploadHeader, uploadHeaderSchema } from './uploadHeader';

export interface V3MarketingContactsImportsResponse {
  /** The ID of the import job. */
  jobId?: string;
  /** The URI to PUT the upload file to. */
  uploadUri?: string;
  /** A list of headers that must be included in PUT request. */
  uploadHeaders?: UploadHeader[];
}

export const v3MarketingContactsImportsResponseSchema: Schema<V3MarketingContactsImportsResponse> = object(
  {
    jobId: ['job_id', optional(string())],
    uploadUri: ['upload_uri', optional(string())],
    uploadHeaders: [
      'upload_headers',
      optional(array(lazy(() => uploadHeaderSchema))),
    ],
  }
);
