/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface V3MarketingContactsResponse {
  /** Indicates that the contacts are queued for processing. Check the job status with the "Import Contacts Status" endpoint. */
  jobId?: string;
}

export const v3MarketingContactsResponseSchema: Schema<V3MarketingContactsResponse> = object(
  { jobId: ['job_id', optional(string())] }
);
