/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { FieldTypeEnum, fieldTypeEnumSchema } from './fieldTypeEnum';

export interface V3MarketingFieldDefinitionsRequest {
  name: string;
  fieldType: FieldTypeEnum;
}

export const v3MarketingFieldDefinitionsRequestSchema: Schema<V3MarketingFieldDefinitionsRequest> = object(
  { name: ['name', string()], fieldType: ['field_type', fieldTypeEnumSchema] }
);
