/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface V3MarketingSinglesendsCategoriesResponse {
  /** list of latest one thousand unique categories associated with all Single Sends in ascending order */
  categories?: string[];
}

export const v3MarketingSinglesendsCategoriesResponseSchema: Schema<V3MarketingSinglesendsCategoriesResponse> = object(
  { categories: ['categories', optional(array(string()))] }
);
