/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Errors30, errors30Schema } from './errors30';

export interface V3Messages400Error21 {
  errors?: Errors30[];
}

export const v3Messages400Error21Schema: Schema<V3Messages400Error21> = object({
  errors: ['errors', optional(array(lazy(() => errors30Schema)))],
});
