/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Status12Enum, status12EnumSchema } from './status12Enum';

export interface V3MessagesDownloadResponse {
  status?: Status12Enum;
  message?: string;
}

export const v3MessagesDownloadResponseSchema: Schema<V3MessagesDownloadResponse> = object(
  {
    status: ['status', optional(status12EnumSchema)],
    message: ['message', optional(string())],
  }
);
