/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface V3ScopesRequestsResponse {
  /** Request ID */
  id?: number;
  /** Name of group of scopes associated to page teammate is requesting access to */
  scopeGroupName?: string;
  /** Teammate's username */
  username?: string;
  /** Teammate's email */
  email?: string;
  /** Teammate's first name */
  firstName?: string;
  /** Teammate's last name */
  lastName?: string;
}

export const v3ScopesRequestsResponseSchema: Schema<V3ScopesRequestsResponse> = object(
  {
    id: ['id', optional(number())],
    scopeGroupName: ['scope_group_name', optional(string())],
    username: ['username', optional(string())],
    email: ['email', optional(string())],
    firstName: ['first_name', optional(string())],
    lastName: ['last_name', optional(string())],
  }
);
