/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface V3SubusersIpsResponse {
  /** The IP addresses that are assigned to the subuser. */
  ips?: string[];
}

export const v3SubusersIpsResponseSchema: Schema<V3SubusersIpsResponse> = object(
  { ips: ['ips', optional(array(string()))] }
);
