/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, object, optional, Schema, string } from '../schema';

export interface V3SuppressionBouncesRequest {
  /** This parameter allows you to delete **every** email in your bounce list. This should not be used with the emails parameter. */
  deleteAll?: boolean;
  /** Delete multiple emails from your bounce list at the same time. This should not be used with the delete_all parameter. */
  emails?: string[];
}

export const v3SuppressionBouncesRequestSchema: Schema<V3SuppressionBouncesRequest> = object(
  {
    deleteAll: ['delete_all', optional(boolean())],
    emails: ['emails', optional(array(string()))],
  }
);
