/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, object, Schema, string } from '../schema';

export interface V3TeammatesRequest {
  /** New teammate's email */
  email: string;
  /** Set to specify list of scopes that teammate should have. Should be empty if teammate is an admin. */
  scopes: string[];
  /** Set to true if teammate should be an admin user */
  isAdmin: boolean;
}

export const v3TeammatesRequestSchema: Schema<V3TeammatesRequest> = object({
  email: ['email', string()],
  scopes: ['scopes', array(string())],
  isAdmin: ['is_admin', boolean()],
});
