/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface V3TemplatesRequest2 {
  /** The name of the transactional template. */
  name?: string;
}

export const v3TemplatesRequest2Schema: Schema<V3TemplatesRequest2> = object({
  name: ['name', optional(string())],
});
