/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface V3TrackingSettingsOpenRequest {
  /** The new status that you want to set for open tracking. */
  enabled?: boolean;
}

export const v3TrackingSettingsOpenRequestSchema: Schema<V3TrackingSettingsOpenRequest> = object(
  { enabled: ['enabled', optional(boolean())] }
);
