/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Result9, result9Schema } from './result9';

export interface V3TrackingSettingsResponse {
  /** The list of all tracking settings. */
  result?: Result9[];
}

export const v3TrackingSettingsResponseSchema: Schema<V3TrackingSettingsResponse> = object(
  { result: ['result', optional(array(lazy(() => result9Schema)))] }
);
