/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface V3UserEmailResponse {
  /** The email address currently on file for your account. */
  email: string;
}

export const v3UserEmailResponseSchema: Schema<V3UserEmailResponse> = object({
  email: ['email', string()],
});
