/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Errors73, errors73Schema } from './errors73';

export interface V3UserWebhooksEventSettingsSigned500Error1 {
  errors?: Errors73[];
}

export const v3UserWebhooksEventSettingsSigned500Error1Schema: Schema<V3UserWebhooksEventSettingsSigned500Error1> = object(
  { errors: ['errors', optional(array(lazy(() => errors73Schema)))] }
);
