/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface V3ValidationsEmailRequest {
  /** The email address that you want to validate. */
  email: string;
  /** A one-word classifier for where this validation originated. */
  source?: string;
}

export const v3ValidationsEmailRequestSchema: Schema<V3ValidationsEmailRequest> = object(
  { email: ['email', string()], source: ['source', optional(string())] }
);
