/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Results1, results1Schema } from './results1';

export interface V3VerifiedSendersStepsCompletedResponse {
  results?: Results1;
}

export const v3VerifiedSendersStepsCompletedResponseSchema: Schema<V3VerifiedSendersStepsCompletedResponse> = object(
  { results: ['results', optional(lazy(() => results1Schema))] }
);
