/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  VerifiedSenderResponseSchema,
  verifiedSenderResponseSchemaSchema,
} from './verifiedSenderResponseSchema';

export interface V3VerifiedSendersResponse {
  results?: VerifiedSenderResponseSchema[];
}

export const v3VerifiedSendersResponseSchema: Schema<V3VerifiedSendersResponse> = object(
  {
    results: [
      'results',
      optional(array(lazy(() => verifiedSenderResponseSchemaSchema))),
    ],
  }
);
