/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for VersionEnum
 */
export enum VersionEnum {
  Enum11 = '1.1',
  Enum12 = '1.2',
  Enum13 = '1.3',
}

/**
 * Schema for VersionEnum
 */
export const versionEnumSchema: Schema<VersionEnum> = stringEnum(VersionEnum);
