/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Warning {
  message?: string;
  field?: string;
  warningId?: string;
}

export const warningSchema: Schema<Warning> = object({
  message: ['message', optional(string())],
  field: ['field', optional(string())],
  warningId: ['warning_id', optional(string())],
});
