/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, numberEnum } from '../schema';

/**
 * Enum for ActiveEnum
 */
export enum ActiveEnum {
  Enum0 = 0,
  Enum1 = 1,
}

/**
 * Schema for ActiveEnum
 */
export const activeEnumSchema: Schema<ActiveEnum> = numberEnum(ActiveEnum);
