/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AggregatedBy11Enum
 */
export enum AggregatedBy11Enum {
  Day = 'day',
  Total = 'total',
}

/**
 * Schema for AggregatedBy11Enum
 */
export const aggregatedBy11EnumSchema: Schema<AggregatedBy11Enum> = stringEnum(AggregatedBy11Enum);
