/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Metadata, metadataSchema } from './metadata';
import { Status2, status2Schema } from './status2';

export interface AllSegmentsResponse {
  /** ID assigned to the segment when created. */
  id: string;
  /** Name of the segment. */
  name: string;
  /** Total number of contacts present in the segment */
  contactsCount: number;
  /** ISO8601 timestamp of when the object was created */
  createdAt: string;
  /** ISO8601 timestamp of when the object was last updated */
  updatedAt: string;
  /** ISO8601 timestamp of when the samples were last updated */
  sampleUpdatedAt: string;
  /** ISO8601 timestamp of when the samples will be next updated */
  nextSampleUpdate: string;
  /** The array of list ids to filter contacts on when building this segment. It allows only one such list id for now. We will support more in future */
  parentListIds: string[];
  /** If not set, segment contains a query for use with Segment v1 APIs. If set to '2', segment contains a SQL query for use in v2. */
  queryVersion: string;
  metadata?: Metadata;
  status: Status2;
}

export const allSegmentsResponseSchema: Schema<AllSegmentsResponse> = object({
  id: ['id', string()],
  name: ['name', string()],
  contactsCount: ['contacts_count', number()],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
  sampleUpdatedAt: ['sample_updated_at', string()],
  nextSampleUpdate: ['next_sample_update', string()],
  parentListIds: ['parent_list_ids', array(string())],
  queryVersion: ['query_version', string()],
  metadata: ['_metadata', optional(lazy(() => metadataSchema))],
  status: ['status', lazy(() => status2Schema)],
});
