/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema';

export interface ARecord {
  /** Indicates if the a_record is valid. */
  valid: boolean;
  /** The type of DNS record. */
  type: string;
  /** This is the web address that will be mapped to the IP address. */
  host: string;
  /** The IP address being set up with Reverse DNS. */
  data: string;
}

export const aRecordSchema: Schema<ARecord> = object({
  valid: ['valid', boolean()],
  type: ['type', string()],
  host: ['host', string()],
  data: ['data', string()],
});
