/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, nullable, object, Schema, string } from '../schema';

export interface ARecord1 {
  /** Indicates if the reverse DNS record could be validated. */
  valid: boolean;
  /** The reason the reverse DNS record could not be validated. Is `null` if the reverse DNS record was validated. */
  reason: string | null;
}

export const aRecord1Schema: Schema<ARecord1> = object({
  valid: ['valid', boolean()],
  reason: ['reason', nullable(string())],
});
