/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema } from '../schema';
import { Metadata1, metadata1Schema } from './metadata1';
import { Results5, results5Schema } from './results5';

export interface AutomationsLinkStatsResponse {
  results: Results5[];
  totalClicks: number;
  metadata: Metadata1;
}

export const automationsLinkStatsResponseSchema: Schema<AutomationsLinkStatsResponse> = object(
  {
    results: ['results', array(lazy(() => results5Schema))],
    totalClicks: ['total_clicks', number()],
    metadata: ['_metadata', lazy(() => metadata1Schema)],
  }
);
