/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, unknown } from '../schema';

/** `billable_breakdown` will only appear to the parent user in an account with subusers. */
export interface BillableBreakdown {
  /** The sum of all the subuser's billable contacts */
  total?: number;
  /** A map of each subuser's billable contact usage. Each key is the subuser's ID and each value is the usage thus far this month. */
  breakdown?: unknown;
}

export const billableBreakdownSchema: Schema<BillableBreakdown> = object({
  total: ['total', optional(number())],
  breakdown: ['breakdown', optional(unknown())],
});
