/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface BlocksResponse {
  /** A Unix timestamp indicating when the email address was added to the blocks list. */
  created: number;
  /** The email address that was added to the block list. */
  email: string;
  /** An explanation for the reason of the block. */
  reason: string;
  /** The status of the block. */
  status: string;
}

export const blocksResponseSchema: Schema<BlocksResponse> = object({
  created: ['created', number()],
  email: ['email', string()],
  reason: ['reason', string()],
  status: ['status', string()],
});
