/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { EditorEnum, editorEnumSchema } from './editorEnum';

export interface CampaignsResponse {
  /** The display title of your campaign. This will be viewable by you in the Marketing Campaigns UI. */
  title: string;
  /** The subject of your campaign that your recipients will see. */
  subject?: string | null;
  /** The ID of the "sender" identity that you have created. Your recipients will see this as the "from" on your marketing emails. */
  senderId?: number | null;
  /** The IDs of the lists you are sending this campaign to. You can have both segment IDs and list IDs */
  listIds?: number[] | null;
  /** The segment IDs that you are sending this list to. You can have both segment IDs and list IDs. Segments are limited to 10 segment IDs. */
  segmentIds?: number[] | null;
  /** The categories you would like associated to this campaign. */
  categories?: string[] | null;
  /** The suppression group that this marketing email belongs to, allowing recipients to opt-out of emails of this type. */
  suppressionGroupId?: number | null;
  /** This is the url of the custom unsubscribe page that you provide for customers to unsubscribe from your suppression groups. */
  customUnsubscribeUrl?: string | null;
  /** The pool of IPs that you would like to send this email from. */
  ipPool?: string | null;
  /** The HTML of your marketing email. */
  htmlContent?: string | null;
  /** The plain text content of your emails. */
  plainContent?: string | null;
  editor?: EditorEnum;
  /** The status of your campaign. */
  status: string;
  id?: number;
}

export const campaignsResponseSchema: Schema<CampaignsResponse> = object({
  title: ['title', string()],
  subject: ['subject', optional(nullable(string()))],
  senderId: ['sender_id', optional(nullable(number()))],
  listIds: ['list_ids', optional(nullable(array(number())))],
  segmentIds: ['segment_ids', optional(nullable(array(number())))],
  categories: ['categories', optional(nullable(array(string())))],
  suppressionGroupId: ['suppression_group_id', optional(nullable(number()))],
  customUnsubscribeUrl: [
    'custom_unsubscribe_url',
    optional(nullable(string())),
  ],
  ipPool: ['ip_pool', optional(nullable(string()))],
  htmlContent: ['html_content', optional(nullable(string()))],
  plainContent: ['plain_content', optional(nullable(string()))],
  editor: ['editor', optional(editorEnumSchema)],
  status: ['status', string()],
  id: ['id', optional(number())],
});
