/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { Status7Enum, status7EnumSchema } from './status7Enum';

export interface Cancelorpauseascheduledsendrequest {
  /** The batch ID is the identifier that your scheduled mail sends share. */
  batchId: string;
  status: Status7Enum;
}

export const cancelorpauseascheduledsendrequestSchema: Schema<Cancelorpauseascheduledsendrequest> = object(
  { batchId: ['batch_id', string()], status: ['status', status7EnumSchema] }
);
