/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Additional2, additional2Schema } from './additional2';
import { Domain2, domain2Schema } from './domain2';
import { LocalPart2, localPart2Schema } from './localPart2';

export interface Checks2 {
  domain: Domain2;
  localPart: LocalPart2;
  additional: Additional2;
}

export const checks2Schema: Schema<Checks2> = object({
  domain: ['domain', lazy(() => domain2Schema)],
  localPart: ['local_part', lazy(() => localPart2Schema)],
  additional: ['additional', lazy(() => additional2Schema)],
});
