/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Metadata1, metadata1Schema } from './metadata1';
import { StatusEnum, statusEnumSchema } from './statusEnum';

export interface ContactExport {
  id: string;
  status: StatusEnum;
  /** The ISO8601 timestamp when the export was begun. */
  createdAt: string;
  /** The ISO8601 timestamp when the export was updated. */
  updatedAt: string;
  /** The ISO8601 timestamp when the export was completed. */
  completedAt?: string;
  /** The ISO8601 timestamp when the exported file on S3 will expire. */
  expiresAt: string;
  /** One or more download URLs for the contact file if the status is `ready`. */
  urls?: string[];
  /** A human readable message if the status is `failure`. */
  message?: string;
  metadata?: Metadata1;
  /** The total number of exported contacts. */
  contactCount?: number;
}

export const contactExportSchema: Schema<ContactExport> = object({
  id: ['id', string()],
  status: ['status', statusEnumSchema],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
  completedAt: ['completed_at', optional(string())],
  expiresAt: ['expires_at', string()],
  urls: ['urls', optional(array(string()))],
  message: ['message', optional(string())],
  metadata: ['_metadata', optional(lazy(() => metadata1Schema))],
  contactCount: ['contact_count', optional(number())],
});
