/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Errors71, errors71Schema } from './errors71';

export interface ContactDBRecipientresponse {
  /** The number of errors found while adding recipients. */
  errorCount: number;
  /** The indices of the recipient(s) sent that caused the error. */
  errorIndices?: number[];
  /** The count of new recipients added to the contactdb. */
  newCount: number;
  /** The recipient IDs of the recipients that already existed from this request. */
  persistedRecipients: string[];
  /** The recipients who were updated from this request. */
  updatedCount: number;
  errors?: Errors71[];
}

export const contactDBRecipientresponseSchema: Schema<ContactDBRecipientresponse> = object(
  {
    errorCount: ['error_count', number()],
    errorIndices: ['error_indices', optional(array(number()))],
    newCount: ['new_count', number()],
    persistedRecipients: ['persisted_recipients', array(string())],
    updatedCount: ['updated_count', number()],
    errors: ['errors', optional(array(lazy(() => errors71Schema)))],
  }
);
