/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Results32, results32Schema } from './results32';

export interface ContactImport {
  /** The job ID. */
  id?: string;
  /** The job state. Allowed values: `pending`, `completed`, `errored`, or `failed`. */
  status?: string;
  /** The job type. Allowed values: `upsert`, or `delete`. */
  jobType?: string;
  results?: Results32;
  /** The ISO8601 timestamp when the job was created. */
  startedAt?: string;
  /** The ISO8601 timestamp when the job was finished. */
  finishedAt?: string;
}

export const contactImportSchema: Schema<ContactImport> = object({
  id: ['id', optional(string())],
  status: ['status', optional(string())],
  jobType: ['job_type', optional(string())],
  results: ['results', optional(lazy(() => results32Schema))],
  startedAt: ['started_at', optional(string())],
  finishedAt: ['finished_at', optional(string())],
});
