/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface ContactDBlists {
  /** The reference ID of your list. */
  id: number;
  /** The name of your list. Must be unique against all other list and segment names. */
  name: string;
  /** The count of recipients currently in the list. */
  recipientCount: number;
}

export const contactDBlistsSchema: Schema<ContactDBlists> = object({
  id: ['id', number()],
  name: ['name', string()],
  recipientCount: ['recipient_count', number()],
});
