/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CountryEnum
 */
export enum CountryEnum {
  US = 'US',
  CA = 'CA',
}

/**
 * Schema for CountryEnum
 */
export const countryEnumSchema: Schema<CountryEnum> = stringEnum(CountryEnum);
