/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Dkim4, dkim4Schema } from './dkim4';
import { DomainSpf2, domainSpf2Schema } from './domainSpf2';
import { MailServer2, mailServer2Schema } from './mailServer2';
import { SubdomainSpf2, subdomainSpf2Schema } from './subdomainSpf2';

export interface Dns4 {
  mailServer: MailServer2;
  subdomainSpf: SubdomainSpf2;
  domainSpf: DomainSpf2;
  dkim: Dkim4;
}

export const dns4Schema: Schema<Dns4> = object({
  mailServer: ['mail_server', lazy(() => mailServer2Schema)],
  subdomainSpf: ['subdomain_spf', lazy(() => subdomainSpf2Schema)],
  domainSpf: ['domain_spf', lazy(() => domainSpf2Schema)],
  dkim: ['dkim', lazy(() => dkim4Schema)],
});
