/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema';
import { TypeEnum, typeEnumSchema } from './typeEnum';

export interface DomainCname3 {
  /** Indicates if the DNS record is valid. */
  valid: boolean;
  type: TypeEnum;
  /** The domain that this link branding will use for the links in your email. */
  host: string;
  /** The domain that the DNS record points to. */
  data: string;
}

export const domainCname3Schema: Schema<DomainCname3> = object({
  valid: ['valid', boolean()],
  type: ['type', typeEnumSchema],
  host: ['host', string()],
  data: ['data', string()],
});
