/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';
import { VersionEnum, versionEnumSchema } from './versionEnum';

export interface EnforcedTLSRequestResponse {
  /** Indicates if you want to require your recipients to support TLS. */
  requireTls?: boolean;
  /** Indicates if you want to require your recipients to have a valid certificate. */
  requireValidCert?: boolean;
  version?: VersionEnum;
}

export const enforcedTLSRequestResponseSchema: Schema<EnforcedTLSRequestResponse> = object(
  {
    requireTls: ['require_tls', optional(boolean())],
    requireValidCert: ['require_valid_cert', optional(boolean())],
    version: ['version', optional(versionEnumSchema)],
  }
);
