/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema';

export interface Errors77 {
  message?: string;
  field?: string;
  help?: unknown;
}

export const errors77Schema: Schema<Errors77> = object({
  message: ['message', optional(string())],
  field: ['field', optional(string())],
  help: ['help', optional(unknown())],
});
