/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Errors42 {
  field?: string;
  message?: string;
  errorId?: string;
}

export const errors42Schema: Schema<Errors42> = object({
  field: ['field', optional(string())],
  message: ['message', optional(string())],
  errorId: ['error_id', optional(string())],
});
