/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Errors2 {
  /** The name of the error. */
  field?: string;
  /** A message explaining why the IP addresses could not be listed. */
  message?: string;
}

export const errors2Schema: Schema<Errors2> = object({
  field: ['field', optional(string())],
  message: ['message', optional(string())],
});
