/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Errors19 {
  message: string;
  errorId: string;
}

export const errors19Schema: Schema<Errors19> = object({
  message: ['message', string()],
  errorId: ['error_id', string()],
});
