/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface From1 {
  /** The email address from which your recipient will receive emails. */
  email?: string;
  /** The name appended to the from email field. Typically your name or company name. */
  name?: string;
}

export const from1Schema: Schema<From1> = object({
  email: ['email', optional(string())],
  name: ['name', optional(string())],
});
