/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';
import { Type6Enum, type6EnumSchema } from './type6Enum';

export interface GETUserAccountresponse {
  type: Type6Enum;
  /** The sender reputation for this user. */
  reputation: number;
}

export const gETUserAccountresponseSchema: Schema<GETUserAccountresponse> = object(
  { type: ['type', type6EnumSchema], reputation: ['reputation', number()] }
);
