/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Ip {
  /** An IP address that you want to allow. */
  ip: string;
}

export const ipSchema: Schema<Ip> = object({ ip: ['ip', string()] });
