/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Result, resultSchema } from './result';

export interface IPAccessResponse {
  /** An array listing all of your allowed IPs. */
  result?: Result[];
}

export const iPAccessResponseSchema: Schema<IPAccessResponse> = object({
  result: ['result', optional(array(lazy(() => resultSchema)))],
});
