/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface IPPoolsPoolResp {
  /** The name of the IP pool. */
  name?: string;
}

export const iPPoolsPoolRespSchema: Schema<IPPoolsPoolResp> = object({
  name: ['name', optional(string())],
});
