/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { SelfMetadata, selfMetadataSchema } from './selfMetadata';

export interface List1 {
  /** The generated ID for your list. */
  id?: string;
  /** The name you gave your list. */
  name?: string;
  /** The number of contacts currently stored on the list. */
  contactCount?: number;
  metadata?: SelfMetadata;
}

export const list1Schema: Schema<List1> = object({
  id: ['id', optional(string())],
  name: ['name', optional(string())],
  contactCount: ['contact_count', optional(number())],
  metadata: ['_metadata', optional(lazy(() => selfMetadataSchema))],
});
