/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema } from '../schema';

/** Checks on the local part of the email address. */
export interface LocalPart {
  /** Whether the local part of email appears to be a role or group (e.g., hr, admin) */
  isSuspectedRoleAddress: boolean;
}

export const localPartSchema: Schema<LocalPart> = object({
  isSuspectedRoleAddress: ['is_suspected_role_address', boolean()],
});
