/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema';

export interface MailServer2 {
  /** The domain sending the messages. */
  host: string;
  /** They type of DNS record. */
  type: string;
  /** The mail server responsible for accepting messages from the sending domain. */
  data: string;
  /** Indicates if this is a valid DNS record. */
  valid: boolean;
}

export const mailServer2Schema: Schema<MailServer2> = object({
  host: ['host', string()],
  type: ['type', string()],
  data: ['data', string()],
  valid: ['valid', boolean()],
});
