/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  BypassBounceManagement2,
  bypassBounceManagement2Schema,
} from './bypassBounceManagement2';
import {
  BypassListManagement2,
  bypassListManagement2Schema,
} from './bypassListManagement2';
import {
  BypassSpamManagement2,
  bypassSpamManagement2Schema,
} from './bypassSpamManagement2';
import {
  BypassUnsubscribeManagement2,
  bypassUnsubscribeManagement2Schema,
} from './bypassUnsubscribeManagement2';
import { Footer2, footer2Schema } from './footer2';
import { SandboxMode2, sandboxMode2Schema } from './sandboxMode2';

export interface MailSettings2 {
  bypassListManagement?: BypassListManagement2;
  bypassSpamManagement?: BypassSpamManagement2;
  bypassBounceManagement?: BypassBounceManagement2;
  bypassUnsubscribeManagement?: BypassUnsubscribeManagement2;
  footer?: Footer2;
  sandboxMode?: SandboxMode2;
}

export const mailSettings2Schema: Schema<MailSettings2> = object({
  bypassListManagement: [
    'bypass_list_management',
    optional(lazy(() => bypassListManagement2Schema)),
  ],
  bypassSpamManagement: [
    'bypass_spam_management',
    optional(lazy(() => bypassSpamManagement2Schema)),
  ],
  bypassBounceManagement: [
    'bypass_bounce_management',
    optional(lazy(() => bypassBounceManagement2Schema)),
  ],
  bypassUnsubscribeManagement: [
    'bypass_unsubscribe_management',
    optional(lazy(() => bypassUnsubscribeManagement2Schema)),
  ],
  footer: ['footer', optional(lazy(() => footer2Schema))],
  sandboxMode: ['sandbox_mode', optional(lazy(() => sandboxMode2Schema))],
});
