/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, nullable, number, object, optional, Schema } from '../schema';

export interface MailSettingsBouncePurge {
  /** Indicates if the bounce purge mail setting is enabled. */
  enabled?: boolean;
  /** The number of days after which SendGrid will purge all contacts from your soft bounces suppression lists. */
  softBounces?: number | null;
  /** The number of days after which SendGrid will purge all contacts from your hard bounces suppression lists. */
  hardBounces?: number | null;
}

export const mailSettingsBouncePurgeSchema: Schema<MailSettingsBouncePurge> = object(
  {
    enabled: ['enabled', optional(boolean())],
    softBounces: ['soft_bounces', optional(nullable(number()))],
    hardBounces: ['hard_bounces', optional(nullable(number()))],
  }
);
