/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Metadata2 {
  prev?: string;
  self?: string;
  next?: string;
}

export const metadata2Schema: Schema<Metadata2> = object({
  prev: ['prev', optional(string())],
  self: ['self', optional(string())],
  next: ['next', optional(string())],
});
