/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface Metrics5 {
  /** The number of links that were clicked in your emails. */
  clicks?: number;
  /** The number of unique recipients who clicked links in your emails. */
  uniqueClicks?: number;
  /** The total number of times your emails were opened by recipients. */
  opens?: number;
  /** The number of unique recipients who opened your emails. */
  uniqueOpens?: number;
}

export const metrics5Schema: Schema<Metrics5> = object({
  clicks: ['clicks', optional(number())],
  uniqueClicks: ['unique_clicks', optional(number())],
  opens: ['opens', optional(number())],
  uniqueOpens: ['unique_opens', optional(number())],
});
