/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { CustomFields1, customFields1Schema } from './customFields1';

export interface Recipient1 {
  createdAt?: number;
  email?: string;
  id?: string;
  lastEmailed?: number;
  lastClicked?: number;
  lastOpened?: number;
  customFields?: CustomFields1[];
  updatedAt?: number;
  firstName?: string;
}

export const recipient1Schema: Schema<Recipient1> = object({
  createdAt: ['created_at', optional(number())],
  email: ['email', optional(string())],
  id: ['id', optional(string())],
  lastEmailed: ['last_emailed', optional(number())],
  lastClicked: ['last_clicked', optional(number())],
  lastOpened: ['last_opened', optional(number())],
  customFields: [
    'custom_fields',
    optional(array(lazy(() => customFields1Schema))),
  ],
  updatedAt: ['updated_at', optional(number())],
  firstName: ['first_name', optional(string())],
});
