/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  ContactDBCustomfieldschema,
  contactDBCustomfieldschemaSchema,
} from './contactDBCustomfieldschema';

export interface Recipient {
  /** The ID of this recipient. */
  id?: string;
  /** The time this record was created in your contactdb, in unixtime. */
  createdAt?: number;
  /** The custom fields assigned to this recipient and their values. */
  customFields?: ContactDBCustomfieldschema[];
  /** The email address of this recipient. This is a default custom field that SendGrid provides. */
  email: string;
  /** The first name of this recipient. This is a default custom field that SendGrid provides. */
  firstName?: string | null;
  /** The last name of the recipient. */
  lastName?: string | null;
  /** The last time this recipient clicked a link from one of your campaigns, in unixtime. */
  lastClicked?: number | null;
  /** The last time this user was emailed by one of your campaigns, in unixtime. */
  lastEmailed?: number | null;
  /** The last time this recipient opened an email from you, in unixtime. */
  lastOpened?: number | null;
  /** The last update date for this recipient's record. */
  updatedAt?: number;
}

export const recipientSchema: Schema<Recipient> = object({
  id: ['id', optional(string())],
  createdAt: ['created_at', optional(number())],
  customFields: [
    'custom_fields',
    optional(array(lazy(() => contactDBCustomfieldschemaSchema))),
  ],
  email: ['email', string()],
  firstName: ['first_name', optional(nullable(string()))],
  lastName: ['last_name', optional(nullable(string()))],
  lastClicked: ['last_clicked', optional(nullable(number()))],
  lastEmailed: ['last_emailed', optional(nullable(number()))],
  lastOpened: ['last_opened', optional(nullable(number()))],
  updatedAt: ['updated_at', optional(number())],
});
