/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ReplyTo1 {
  /** The email address to which your recipient will reply. */
  email?: string;
  /** The name appended to the reply to email field. Typically your name or company name. */
  name?: string;
}

export const replyTo1Schema: Schema<ReplyTo1> = object({
  email: ['email', optional(string())],
  name: ['name', optional(string())],
});
