/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface Result7 {
  /** Email address teammate invite will be sent to */
  email?: string;
  /** List of permissions to give teammate if they accept */
  scopes?: string[];
  /** Set to true to indicate teammate should have the same set of permissions as parent user */
  isAdmin?: boolean;
  /** Invitation token used to identify user */
  token?: string;
  /** timestamp indicates when invite will expire. Expiration is 7 days after invite creation */
  expirationDate?: number;
}

export const result7Schema: Schema<Result7> = object({
  email: ['email', optional(string())],
  scopes: ['scopes', optional(array(string()))],
  isAdmin: ['is_admin', optional(boolean())],
  token: ['token', optional(string())],
  expirationDate: ['expiration_date', optional(number())],
});
