/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { Checks2, checks2Schema } from './checks2';
import { VerdictEnum, verdictEnumSchema } from './verdictEnum';

export interface Result2 {
  /** The email being validated */
  email: string;
  verdict: VerdictEnum;
  /** A numeric representation of the email validity. */
  score: number;
  /** The local part of the email address. */
  local: string;
  /** The domain of the email address. */
  host: string;
  /** A suggested correction in the event of domain name typos (e.g., gmial.com) */
  suggestion?: string;
  checks: Checks2;
  /** The source of the validation, as per the API request. */
  source?: string;
  /** The IP address associated with this email. */
  ipAddress: string;
}

export const result2Schema: Schema<Result2> = object({
  email: ['email', string()],
  verdict: ['verdict', verdictEnumSchema],
  score: ['score', number()],
  local: ['local', string()],
  host: ['host', string()],
  suggestion: ['suggestion', optional(string())],
  checks: ['checks', lazy(() => checks2Schema)],
  source: ['source', optional(string())],
  ipAddress: ['ip_address', string()],
});
