/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema';

export interface Result5 {
  /** The title of the partner. */
  title: string;
  /** Indicates if this partner setting has been enabled. */
  enabled: boolean;
  /** The name of the partner setting. */
  name: string;
  /** A description of this partner setting. */
  description: string;
}

export const result5Schema: Schema<Result5> = object({
  title: ['title', string()],
  enabled: ['enabled', boolean()],
  name: ['name', string()],
  description: ['description', string()],
});
