/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { List, listSchema } from './list';
import { Metadata2, metadata2Schema } from './metadata2';
import { Segment, segmentSchema } from './segment';

export interface Result8 {
  /** Export jobs ID. */
  id?: string;
  /** Allowed values: `pending`, `ready`, or `failure`. */
  status?: string;
  /** This ISO8601 timestamp when the export was created. */
  createdAt?: string;
  /** This ISO8601 timestamp when the export was completed. */
  completedAt?: string;
  /** This ISO8601 timestamp when the export expires. */
  expiresAt?: string;
  /** One or more download URLs for the contact file(s) if the status is `ready`. */
  urls?: string[];
  /** User ID. */
  userId?: string;
  /** Allowed types: `contacts_export`, `list_export`, or `segment_export`. */
  exportType?: string;
  segments?: Segment[];
  lists?: List[];
  metadata?: Metadata2;
}

export const result8Schema: Schema<Result8> = object({
  id: ['id', optional(string())],
  status: ['status', optional(string())],
  createdAt: ['created_at', optional(string())],
  completedAt: ['completed_at', optional(string())],
  expiresAt: ['expires_at', optional(string())],
  urls: ['urls', optional(array(string()))],
  userId: ['user_id', optional(string())],
  exportType: ['export_type', optional(string())],
  segments: ['segments', optional(array(lazy(() => segmentSchema)))],
  lists: ['lists', optional(array(lazy(() => listSchema)))],
  metadata: ['_metadata', optional(lazy(() => metadata2Schema))],
});
