/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema, string } from '../schema';
import { ContactResponse, contactResponseSchema } from './contactResponse';
import { Status2, status2Schema } from './status2';

export interface SegmentResponse {
  /** ID assigned to the segment when created. */
  id: string;
  /** Name of the segment. */
  name: string;
  /** SQL query which will filter contacts based on the conditions provided */
  queryDsl: string;
  /** Total number of contacts present in the segment */
  contactsCount: number;
  /** A subset of all contacts that are in this segment */
  contactsSample: ContactResponse[];
  /** ISO8601 timestamp of when the object was created */
  createdAt: string;
  /** ISO8601 timestamp of when the object was last updated */
  updatedAt: string;
  /** ISO8601 timestamp of when the samples were last updated */
  sampleUpdatedAt: string;
  /** ISO8601 timestamp of when the samples will be next updated */
  nextSampleUpdate: string;
  /** The array of list ids to filter contacts on when building this segment. It allows only one such list id for now. We will support more in future */
  parentListIds: string[];
  /** If not set, segment contains a Query for use with Segment v1 APIs. If set to '2', segment contains a SQL query for use in v2. */
  queryVersion: string;
  status: Status2;
}

export const segmentResponseSchema: Schema<SegmentResponse> = object({
  id: ['id', string()],
  name: ['name', string()],
  queryDsl: ['query_dsl', string()],
  contactsCount: ['contacts_count', number()],
  contactsSample: ['contacts_sample', array(lazy(() => contactResponseSchema))],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
  sampleUpdatedAt: ['sample_updated_at', string()],
  nextSampleUpdate: ['next_sample_update', string()],
  parentListIds: ['parent_list_ids', array(string())],
  queryVersion: ['query_version', string()],
  status: ['status', lazy(() => status2Schema)],
});
