/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Segment {
  iD?: string;
  name?: string;
}

export const segmentSchema: Schema<Segment> = object({
  iD: ['ID', optional(string())],
  name: ['Name', optional(string())],
});
