/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema } from '../schema';

export interface SettingsClickTracking {
  /** Indicates if click tracking is enabled for plain text emails. */
  enableText: boolean;
  /** Indicates if click tracking is enabled or disabled. */
  enabled: boolean;
}

export const settingsClickTrackingSchema: Schema<SettingsClickTracking> = object(
  { enableText: ['enable_text', boolean()], enabled: ['enabled', boolean()] }
);
