/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';
import { Status3Enum, status3EnumSchema } from './status3Enum';

export interface SinglesendSearch {
  /** leading and trailing wildcard search on name of the Single Send */
  name?: string;
  /** current status of the Single Send */
  status?: Status3Enum[];
  /** categories to associate with this Single Send, match any single send that has at least one of the categories */
  categories?: string[];
}

export const singlesendSearchSchema: Schema<SinglesendSearch> = object({
  name: ['name', optional(string())],
  status: ['status', optional(array(status3EnumSchema))],
  categories: ['categories', optional(array(string()))],
});
