/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface SpamReportsResponse {
  /** A Unix timestamp that indicates when the recipient marked your message as spam. */
  created: number;
  /** The email address of the recipient that marked your message as spam. */
  email: string;
  /** The IP address that the message was sent from. */
  ip: string;
}

export const spamReportsResponseSchema: Schema<SpamReportsResponse> = object({
  created: ['created', number()],
  email: ['email', string()],
  ip: ['ip', string()],
});
