/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Status7Enum
 */
export enum Status7Enum {
  Pause = 'pause',
  Cancel = 'cancel',
}

/**
 * Schema for Status7Enum
 */
export const status7EnumSchema: Schema<Status7Enum> = stringEnum(Status7Enum);
