/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Metrics5, metrics5Schema } from './metrics5';

export interface Stat4 {
  /** The type of segmentation. */
  type?: string;
  /** The name of the specific segmentation. */
  name?: string;
  metrics?: Metrics5;
}

export const stat4Schema: Schema<Stat4> = object({
  type: ['type', optional(string())],
  name: ['name', optional(string())],
  metrics: ['metrics', optional(lazy(() => metrics5Schema))],
});
