/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Status12Enum
 */
export enum Status12Enum {
  Pending = 'pending',
}

/**
 * Schema for Status12Enum
 */
export const status12EnumSchema: Schema<Status12Enum> = stringEnum(Status12Enum);
