/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Stat, statSchema } from './stat';

export interface SubuserStats {
  /** The date the statistics were gathered. */
  date?: string;
  /** The list of statistics. */
  stats?: Stat[];
}

export const subuserStatsSchema: Schema<SubuserStats> = object({
  date: ['date', optional(string())],
  stats: ['stats', optional(array(lazy(() => statSchema)))],
});
