/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface SuppressionsSuppressionGroup {
  /** The id of the suppression group. */
  id: number;
  /** The name of the suppression group. Each group created by a user must have a unique name. */
  name: string;
  /** A description of the suppression group. */
  description: string;
  lastEmailSentAt?: number | null;
  /** Indicates if this is the default suppression group. */
  isDefault?: boolean;
  /** The unsubscribes associated with this group. */
  unsubscribes?: number;
}

export const suppressionsSuppressionGroupSchema: Schema<SuppressionsSuppressionGroup> = object(
  {
    id: ['id', number()],
    name: ['name', string()],
    description: ['description', string()],
    lastEmailSentAt: ['last_email_sent_at', optional(nullable(number()))],
    isDefault: ['is_default', optional(boolean())],
    unsubscribes: ['unsubscribes', optional(number())],
  }
);
