/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface SuppressionGroupRequestBase {
  /** The name of your suppression group. Required when creating a group. */
  name?: string;
  /** A brief description of your suppression group. Required when creating a group. */
  description?: string;
  /** Indicates if you would like this to be your default suppression group. */
  isDefault?: boolean;
}

export const suppressionGroupRequestBaseSchema: Schema<SuppressionGroupRequestBase> = object(
  {
    name: ['name', optional(string())],
    description: ['description', optional(string())],
    isDefault: ['is_default', optional(boolean())],
  }
);
