/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { ClickTracking2, clickTracking2Schema } from './clickTracking2';
import { Ganalytics2, ganalytics2Schema } from './ganalytics2';
import { OpenTracking2, openTracking2Schema } from './openTracking2';
import {
  SubscriptionTracking2,
  subscriptionTracking2Schema,
} from './subscriptionTracking2';

/** Settings to determine how you would like to track the metrics of how your recipients interact with your email. */
export interface TrackingSettings {
  clickTracking?: ClickTracking2;
  openTracking?: OpenTracking2;
  subscriptionTracking?: SubscriptionTracking2;
  ganalytics?: Ganalytics2;
}

export const trackingSettingsSchema: Schema<TrackingSettings> = object({
  clickTracking: ['click_tracking', optional(lazy(() => clickTracking2Schema))],
  openTracking: ['open_tracking', optional(lazy(() => openTracking2Schema))],
  subscriptionTracking: [
    'subscription_tracking',
    optional(lazy(() => subscriptionTracking2Schema)),
  ],
  ganalytics: ['ganalytics', optional(lazy(() => ganalytics2Schema))],
});
