/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface V3ApiKeysRequest1 {
  /** The new name of the API Key. */
  name: string;
}

export const v3ApiKeysRequest1Schema: Schema<V3ApiKeysRequest1> = object({
  name: ['name', string()],
});
