/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface V3ApiKeysRequest2 {
  name: string;
  scopes?: string[];
}

export const v3ApiKeysRequest2Schema: Schema<V3ApiKeysRequest2> = object({
  name: ['name', string()],
  scopes: ['scopes', optional(array(string()))],
});
