/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface V3AsmGroupsSuppressionsResponse {
  /** The email addresses you added to the unsubscribe group */
  recipientEmails?: string[];
}

export const v3AsmGroupsSuppressionsResponseSchema: Schema<V3AsmGroupsSuppressionsResponse> = object(
  { recipientEmails: ['recipient_emails', optional(array(string()))] }
);
