/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface V3CategoriesResponse {
  /** A category used to group emails by broad topic. */
  category: string;
}

export const v3CategoriesResponseSchema: Schema<V3CategoriesResponse> = object({
  category: ['category', string()],
});
