/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import { Recipient1, recipient1Schema } from './recipient1';

export interface V3ContactdbRecipientsSearchResponse1 {
  recipients?: Recipient1[];
  recipientCount?: number;
}

export const v3ContactdbRecipientsSearchResponse1Schema: Schema<V3ContactdbRecipientsSearchResponse1> = object(
  {
    recipients: ['recipients', optional(array(lazy(() => recipient1Schema)))],
    recipientCount: ['recipient_count', optional(number())],
  }
);
