/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface V3IpsPoolsRequest1 {
  /** The new name for your IP pool. */
  name?: string;
}

export const v3IpsPoolsRequest1Schema: Schema<V3IpsPoolsRequest1> = object({
  name: ['name', optional(string())],
});
