/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, number, object, Schema, string } from '../schema';

export interface V3IpsPoolsIpsResponse {
  /** The IP address. */
  ip: string;
  /** The IP pools that this IP address has been added to. */
  pools: string[];
  /** A Unix timestamp indicating when the warmup process began for the added IP address. */
  startDate: number;
  /** Indicates if the IP address is in warmup. */
  warmup: boolean;
}

export const v3IpsPoolsIpsResponseSchema: Schema<V3IpsPoolsIpsResponse> = object(
  {
    ip: ['ip', string()],
    pools: ['pools', array(string())],
    startDate: ['start_date', number()],
    warmup: ['warmup', boolean()],
  }
);
