/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Error5, error5Schema } from './error5';

export interface V3IpsWarmup404Error21 {
  /** The errors that were encountered. */
  errors?: Error5[];
}

export const v3IpsWarmup404Error21Schema: Schema<V3IpsWarmup404Error21> = object(
  { errors: ['errors', optional(array(lazy(() => error5Schema)))] }
);
