/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { ContactDetails3, contactDetails3Schema } from './contactDetails3';

export interface V3MarketingContactsBatchResponse {
  result?: ContactDetails3[];
}

export const v3MarketingContactsBatchResponseSchema: Schema<V3MarketingContactsBatchResponse> = object(
  { result: ['result', optional(array(lazy(() => contactDetails3Schema)))] }
);
