/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { FieldTypeEnum, fieldTypeEnumSchema } from './fieldTypeEnum';
import { Metadata, metadataSchema } from './metadata';

export interface V3MarketingFieldDefinitionsResponse {
  id: string;
  name: string;
  fieldType: FieldTypeEnum;
  metadata?: Metadata;
}

export const v3MarketingFieldDefinitionsResponseSchema: Schema<V3MarketingFieldDefinitionsResponse> = object(
  {
    id: ['id', string()],
    name: ['name', string()],
    fieldType: ['field_type', fieldTypeEnumSchema],
    metadata: ['_metadata', optional(lazy(() => metadataSchema))],
  }
);
