/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { From, fromSchema } from './from';
import { ReplyTo, replyToSchema } from './replyTo';

export interface V3MarketingSendersRequest {
  /** A nickname for the sender identity. Not used for sending. */
  nickname: string;
  from: From;
  replyTo?: ReplyTo;
  /** The physical address of the sender identity. */
  address: string;
  /** Additional sender identity address information. */
  address2?: string;
  /** The city of the sender identity. */
  city: string;
  /** The state of the sender identity. */
  state?: string;
  /** The zipcode of the sender identity. */
  zip?: string;
  /** The country of the sender identity. */
  country: string;
}

export const v3MarketingSendersRequestSchema: Schema<V3MarketingSendersRequest> = object(
  {
    nickname: ['nickname', string()],
    from: ['from', lazy(() => fromSchema)],
    replyTo: ['reply_to', optional(lazy(() => replyToSchema))],
    address: ['address', string()],
    address2: ['address_2', optional(string())],
    city: ['city', string()],
    state: ['state', optional(string())],
    zip: ['zip', optional(string())],
    country: ['country', string()],
  }
);
