/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Metadata1, metadata1Schema } from './metadata1';

export interface V3MarketingContactsExportsResponse {
  metadata: Metadata1;
  /** The ID of the export job. */
  id?: string;
}

export const v3MarketingContactsExportsResponseSchema: Schema<V3MarketingContactsExportsResponse> = object(
  {
    metadata: ['_metadata', lazy(() => metadata1Schema)],
    id: ['id', optional(string())],
  }
);
