/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { List1, list1Schema } from './list1';
import { Metadata1, metadata1Schema } from './metadata1';

export interface V3MarketingListsResponse {
  result?: List1[];
  metadata?: Metadata1;
}

export const v3MarketingListsResponseSchema: Schema<V3MarketingListsResponse> = object(
  {
    result: ['result', optional(array(lazy(() => list1Schema)))],
    metadata: ['_metadata', optional(lazy(() => metadata1Schema))],
  }
);
