/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Metadata3, metadata3Schema } from './metadata3';
import { Result8, result8Schema } from './result8';

export interface V3MarketingContactsExportsResponse1 {
  result?: Result8[];
  metadata?: Metadata3;
}

export const v3MarketingContactsExportsResponse1Schema: Schema<V3MarketingContactsExportsResponse1> = object(
  {
    result: ['result', optional(array(lazy(() => result8Schema)))],
    metadata: ['_metadata', optional(lazy(() => metadata3Schema))],
  }
);
