/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, unknown } from '../schema';

/** The deletion job has been accepted and is being processed. */
export interface V3MarketingContactsResponse1 {
  /** The deletion job ID. */
  jobId?: unknown;
}

export const v3MarketingContactsResponse1Schema: Schema<V3MarketingContactsResponse1> = object(
  { jobId: ['job_id', unknown()] }
);
