/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Errors34, errors34Schema } from './errors34';

export interface V3Messages400Error1 {
  errors: Errors34[];
}

export const v3Messages400Error1Schema: Schema<V3Messages400Error1> = object({
  errors: ['errors', array(lazy(() => errors34Schema))],
});
