/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface V3ScopesResponse {
  /** The list of scopes for which this user has access. */
  scopes: string[];
}

export const v3ScopesResponseSchema: Schema<V3ScopesResponse> = object({
  scopes: ['scopes', array(string())],
});
