/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Result10, result10Schema } from './result10';

export interface V3SuppressionBouncesClassificationsResponse {
  result?: Result10[];
}

export const v3SuppressionBouncesClassificationsResponseSchema: Schema<V3SuppressionBouncesClassificationsResponse> = object(
  { result: ['result', optional(array(lazy(() => result10Schema)))] }
);
