/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Result11, result11Schema } from './result11';

export interface V3SuppressionBouncesClassificationsResponse1 {
  result?: Result11[];
}

export const v3SuppressionBouncesClassificationsResponse1Schema: Schema<V3SuppressionBouncesClassificationsResponse1> = object(
  { result: ['result', optional(array(lazy(() => result11Schema)))] }
);
