/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface V3TeammatesResponse {
  /** Token to identify invite */
  token?: string;
  /** Teammate's email address */
  email?: string;
  /** Initial set of permissions to give to teammate if they accept the invite */
  scopes?: unknown[];
  /** Set to true if teammate should have admin privileges */
  isAdmin?: boolean;
}

export const v3TeammatesResponseSchema: Schema<V3TeammatesResponse> = object({
  token: ['token', optional(string())],
  email: ['email', optional(string())],
  scopes: ['scopes', optional(array(unknown()))],
  isAdmin: ['is_admin', optional(boolean())],
});
