/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface V3TrackingSettingsClickRequest {
  /** The setting you want to use for click tracking. */
  enabled?: boolean;
}

export const v3TrackingSettingsClickRequestSchema: Schema<V3TrackingSettingsClickRequest> = object(
  { enabled: ['enabled', optional(boolean())] }
);
