/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema } from '../schema';
import { Status9Enum, status9EnumSchema } from './status9Enum';

export interface V3UserScheduledSendsRequest {
  status: Status9Enum;
}

export const v3UserScheduledSendsRequestSchema: Schema<V3UserScheduledSendsRequest> = object(
  { status: ['status', status9EnumSchema] }
);
