/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface V3UserPasswordRequest {
  /** The new password you would like to use for your account. */
  newPassword: string;
  /** The old password for your account. */
  oldPassword: string;
}

export const v3UserPasswordRequestSchema: Schema<V3UserPasswordRequest> = object(
  {
    newPassword: ['new_password', string()],
    oldPassword: ['old_password', string()],
  }
);
