/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface V3UserUsernameResponse {
  /** Your account username. */
  username: string;
  /** The user ID for your account. */
  userId: number;
}

export const v3UserUsernameResponseSchema: Schema<V3UserUsernameResponse> = object(
  { username: ['username', string()], userId: ['user_id', number()] }
);
