/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Result2, result2Schema } from './result2';

export interface V3ValidationsEmailResponse {
  result: Result2;
}

export const v3ValidationsEmailResponseSchema: Schema<V3ValidationsEmailResponse> = object(
  { result: ['result', lazy(() => result2Schema)] }
);
