/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, number, object, optional, Schema } from '../schema';
import {
  ValidationResults3,
  validationResults3Schema,
} from './validationResults3';

export interface V3WhitelabelDomainsValidateResponse {
  /** The ID of the authenticated domain. */
  id?: number;
  /** Indicates if this is a valid authenticated domain. */
  valid?: boolean;
  validationResults?: ValidationResults3;
}

export const v3WhitelabelDomainsValidateResponseSchema: Schema<V3WhitelabelDomainsValidateResponse> = object(
  {
    id: ['id', optional(number())],
    valid: ['valid', optional(boolean())],
    validationResults: [
      'validation_results',
      optional(lazy(() => validationResults3Schema)),
    ],
  }
);
