/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface V3WhitelabelDomainsRequest1 {
  /** Indicates whether this is the default authenticated domain. */
  mDefault?: boolean;
  /** Indicates whether to generate a custom SPF record for manual security. */
  customSpf?: boolean;
}

export const v3WhitelabelDomainsRequest1Schema: Schema<V3WhitelabelDomainsRequest1> = object(
  {
    mDefault: ['default', optional(boolean())],
    customSpf: ['custom_spf', optional(boolean())],
  }
);
