/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, number, object, Schema } from '../schema';
import {
  ValidationResults4,
  validationResults4Schema,
} from './validationResults4';

export interface V3WhitelabelLinksValidateResponse {
  /** The ID of the branded link. */
  id: number;
  /** Indicates if the link branding is valid. */
  valid: boolean;
  validationResults: ValidationResults4;
}

export const v3WhitelabelLinksValidateResponseSchema: Schema<V3WhitelabelLinksValidateResponse> = object(
  {
    id: ['id', number()],
    valid: ['valid', boolean()],
    validationResults: [
      'validation_results',
      lazy(() => validationResults4Schema),
    ],
  }
);
