/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { ARecord1, aRecord1Schema } from './aRecord1';

export interface ValidationResults22 {
  aRecord?: ARecord1;
}

export const validationResults22Schema: Schema<ValidationResults22> = object({
  aRecord: ['a_record', optional(lazy(() => aRecord1Schema))],
});
