/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for VerdictEnum
 */
export enum VerdictEnum {
  Valid = 'Valid',
  Risky = 'Risky',
  Invalid = 'Invalid',
}

/**
 * Schema for VerdictEnum
 */
export const verdictEnumSchema: Schema<VerdictEnum> = stringEnum(VerdictEnum);
