/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Error9 } from '../models/error9';

/**
 * Creates an instance of Errors281
 */
interface Errors281 {
  errors?: Error9[];
}

export class Errors281Error extends ApiError<Errors281> {}
