/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of V3IpsPools404Error4
 */
interface V3IpsPools404Error4 {
  /** An error explaining why the pool could not be deleted. */
  error?: string;
}

export class V3IpsPools404Error4Error extends ApiError<V3IpsPools404Error4> {}
