/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Error5 } from '../models/error5';

/**
 * Creates an instance of V3IpsWarmup404Error3
 */
interface V3IpsWarmup404Error3 {
  /** The errors that were encountered. */
  errors?: Error5[];
}

export class V3IpsWarmup404Error3Error extends ApiError<V3IpsWarmup404Error3> {}
