/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors4 } from '../models/errors4';

/**
 * Creates an instance of V3MailSettings404Error1
 */
interface V3MailSettings404Error1 {
  errors?: Errors4[];
}

export class V3MailSettings404Error1Error extends ApiError<V3MailSettings404Error1> {}
