/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Error10 } from '../models/error10';

/**
 * Creates an instance of V3MarketingContactsImports400Error21
 */
interface V3MarketingContactsImports400Error21 {
  errors?: Error10;
}

export class V3MarketingContactsImports400Error21Error extends ApiError<V3MarketingContactsImports400Error21> {}
