/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors42 } from '../models/errors42';

/**
 * Creates an instance of V3MarketingSinglesendsCategories500Error1
 */
interface V3MarketingSinglesendsCategories500Error1 {
  errors?: Errors42[];
}

export class V3MarketingSinglesendsCategories500Error1Error extends ApiError<V3MarketingSinglesendsCategories500Error1> {}
