/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors36 } from '../models/errors36';

/**
 * Creates an instance of V3MarketingSegments404Error1
 */
interface V3MarketingSegments404Error1 {
  errors: Errors36[];
}

export class V3MarketingSegments404Error1Error extends ApiError<V3MarketingSegments404Error1> {}
