/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of V3MarketingLists404Error1
 */
interface V3MarketingLists404Error1 {
  errors: unknown[];
}

export class V3MarketingLists404Error1Error extends ApiError<V3MarketingLists404Error1> {}
