/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of V3MarketingContacts400Error21
 */
interface V3MarketingContacts400Error21 {
  errors: unknown[];
}

export class V3MarketingContacts400Error21Error extends ApiError<V3MarketingContacts400Error21> {}
