/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors33 } from '../models/errors33';

/**
 * Creates an instance of V3MarketingSegments20500
 */
interface V3MarketingSegments20500 {
  errors: Errors33[];
}

export class V3MarketingSegments20500Error extends ApiError<V3MarketingSegments20500> {}
