/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors72 } from '../models/errors72';

/**
 * Creates an instance of V3Templates400Error1
 */
interface V3Templates400Error1 {
  errors?: Errors72[];
}

export class V3Templates400Error1Error extends ApiError<V3Templates400Error1> {}
