/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors9 } from '../models/errors9';

/**
 * Creates an instance of V3Teammates400Error1
 */
interface V3Teammates400Error1 {
  errors?: Errors9[];
}

export class V3Teammates400Error1Error extends ApiError<V3Teammates400Error1> {}
