/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of V3Alerts400Error1
 */
interface V3Alerts400Error1 {
  field?: string;
  message?: string;
}

export class V3Alerts400Error1Error extends ApiError<V3Alerts400Error1> {}
