/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors1 } from '../models/errors1';

/**
 * Creates an instance of V3IpsPoolsIps404
 */
interface V3IpsPoolsIps404 {
  /** The error returned. */
  errors?: Errors1[];
}

export class V3IpsPoolsIps404Error extends ApiError<V3IpsPoolsIps404> {}
