/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors3 } from '../models/errors3';

/**
 * Creates an instance of V3IpsPools404Error3
 */
interface V3IpsPools404Error3 {
  errors?: Errors3[];
}

export class V3IpsPools404Error3Error extends ApiError<V3IpsPools404Error3> {}
