/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Error1 } from '../models/error1';

/**
 * Creates an instance of V3MailSend500Error1
 */
interface V3MailSend500Error1 {
  errors?: Error1[];
}

export class V3MailSend500Error1Error extends ApiError<V3MailSend500Error1> {}
