/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors34 } from '../models/errors34';

/**
 * Creates an instance of V3MarketingSegments500Error1
 */
interface V3MarketingSegments500Error1 {
  errors: Errors34[];
}

export class V3MarketingSegments500Error1Error extends ApiError<V3MarketingSegments500Error1> {}
