/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors77 } from '../models/errors77';

/**
 * Creates an instance of V3MailBatch400Error1
 */
interface V3MailBatch400Error1 {
  errors?: Errors77[];
  id?: string;
}

export class V3MailBatch400Error1Error extends ApiError<V3MailBatch400Error1> {}
