/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Error10 } from '../models/error10';

/**
 * Creates an instance of V3MarketingFieldDefinitions404Error1
 */
interface V3MarketingFieldDefinitions404Error1 {
  errors: Error10[];
}

export class V3MarketingFieldDefinitions404Error1Error extends ApiError<V3MarketingFieldDefinitions404Error1> {}
