/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors73 } from '../models/errors73';

/**
 * Creates an instance of V3UserWebhooksEventSettingsSigned401
 */
interface V3UserWebhooksEventSettingsSigned401 {
  errors?: Errors73[];
}

export class V3UserWebhooksEventSettingsSigned401Error extends ApiError<V3UserWebhooksEventSettingsSigned401> {}
