/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Error8 } from '../models/error8';

/**
 * Creates an instance of V3WhitelabelIpsValidate500
 */
interface V3WhitelabelIpsValidate500 {
  /** The error messages for the failed validation. */
  errors: Error8[];
}

export class V3WhitelabelIpsValidate500Error extends ApiError<V3WhitelabelIpsValidate500> {}
